#!/usr/bin/python3
import jinja2
import sys
import os
from project import Project
from post import Post

class Generator:
    # projects: [Project]
    # posts: [Post]

    def __init__(self, projects_dir, posts_dir, templates_dir):
        self.projects = []
        self.posts = []
        self.env = jinja2.Environment(loader=jinja2.FileSystemLoader(searchpath=templates_dir))

        projects_subdirs = [os.path.join(projects_dir, f) for f in os.listdir(projects_dir) if os.path.isdir(os.path.join(projects_dir, f))]
        for project_dir in projects_subdirs:
            project = Project.load_from_dir(project_dir)
            self.projects.append(project)

        posts_subdirs = [os.path.join(posts_dir, f) for f in os.listdir(posts_dir) if os.path.isdir(os.path.join(posts_dir, f))]
        for post_dir in posts_subdirs:
            post = Post.load_from_dir(post_dir)
            self.posts.append(post)

    def render_template(self, template):
        template = self.env.get_template(template)
        v = {"projects": self.projects, "posts": self.posts}
        return template.render(v)

    def render_index(self, index_path):
        open(index_path, 'w').write(self.render_template("index.html"))

    def render_blog(self, blog_path, posts_dir_path):
        open(blog_path, 'w').write(self.render_template("blog.html"))

if __name__ == "__main__":
    generator = Generator(sys.argv[1], sys.argv[2], sys.argv[3])
    print(generator.render_index())
    #generator.render_template("index.html")

# templateLoader = jinja2.FileSystemLoader(searchpath=)
# templateEnv = jinja2.Environment(loader=templateLoader)
# TEMPLATE_FILE = sys.argv[2]
# template = templateEnv.get_template(TEMPLATE_FILE)
# outputText = template.render()  # this is where to put args to the template renderer

# print(outputText)
